export const CodeGroupSeed = [
  { code: "CM01", name: "여부코드", description: "유무 코드", order_seq: 1, is_use: "Y" },
  { code: "CM02", name: "라이브상태", description: "라이브 상태 코드", order_seq: 2, is_use: "Y" },
  { code: "CM03", name: "채널상태", description: "채널 상태 코드", order_seq: 3, is_use: "Y" },
  { code: "CM04", name: "노드유형", description: "노드 유형 코드", order_seq: 4, is_use: "Y" },
  { code: "CM05", name: "이벤트상태", description: "이벤트상태코드", order_seq: 5, is_use: "Y" },
  { code: "CM06", name: "AWS인스턴스상태", description: "AWS인스턴스상태", order_seq: 6, is_use: "Y" },
  { code: "CM07", name: "리전정보", description: "리전정보", order_seq: 7, is_use: "Y" },
  { code: "CM08", name: "4DLS유형", description: "4인 유형 코드", order_seq: 8, is_use: "Y" },
  { code: "CM09", name: "nodeStatus", description: "nodeStatus", order_seq: 9, is_use: "Y" },
  { code: "CM10", name: "그룹유형", description: "그룹유형", order_seq: 10, is_use: "Y" },
  { code: "CM11", name: "미디어유형", description: "미디어유형", order_seq: 11, is_use: "Y" },
  { code: "CM12", name: "오디오채널유형", description: "오디오채널유형", order_seq: 12, is_use: "Y" },
  { code: "CM13", name: "viewType", description: "viewType", order_seq: 13, is_use: "Y" },
  { code: "CM14", name: "4DML유형", description: "4DML유형", order_seq: 14, is_use: "Y" },
  { code: "CM15", name: "deployType", description: "deployType", order_seq: 15, is_use: "Y" },
];
