// 시드 파일 & 마이그레이션 작성 시 참고 */

// import { Knex } from "knex";
//
// const worldCountries = require("./world_country.json");
// const worldCities = require("./world_city.json");
// const worldStates = require("./world_state.json");
//
// export async function seed(knex: Knex): Promise<void> {
//   // Deletes ALL existing entries
//   await knex("code_common").del();
//
//   // Inserts code_common seed entries
//   await knex("code_common").insert([
//     { group_code: "CM01", code: "CM01Y", name: "Y", description: "Y", order_seq: 1, is_use: "Y" },
//     { group_code: "CM01", code: "CM01N", name: "N", description: "N", order_seq: 2, is_use: "Y" },
//     {
//       group_code: "CM02",
//       code: "CM0201",
//       name: "scheduled",
//       description: "SCHEDULED",
//       order_seq: 1,
//       is_use: "Y",
//     },
//     { group_code: "CM02", code: "CM0202", name: "live", description: "LIVE", order_seq: 2, is_use: "Y" },
//     { group_code: "CM02", code: "CM0203", name: "canceled", description: "CANCELED", order_seq: 3, is_use: "Y" },
//     { group_code: "CM02", code: "CM0204", name: "finished", description: "FINISHED", order_seq: 4, is_use: "Y" },
//     { group_code: "CM03", code: "CM0301", name: "active", description: "ACTIVE", order_seq: 1, is_use: "Y" },
//     { group_code: "CM03", code: "CM0302", name: "inactive", description: "INACTIVE", order_seq: 2, is_use: "Y" },
//     { group_code: "CM04", code: "CM0401", name: "4dc", description: "FDC", order_seq: 1, is_use: "Y" },
//     { group_code: "CM04", code: "CM0402", name: "4drs", description: "FDRS", order_seq: 2, is_use: "Y" },
//     { group_code: "CM04", code: "CM0403", name: "4dsr", description: "FDSR", order_seq: 3, is_use: "Y" },
//     { group_code: "CM04", code: "CM0404", name: "4drm", description: "FDRM", order_seq: 4, is_use: "Y" },
//     { group_code: "CM04", code: "CM0405", name: "4dss", description: "FDSS", order_seq: 5, is_use: "Y" },
//     { group_code: "CM04", code: "CM0406", name: "4dls", description: "FDLS", order_seq: 6, is_use: "Y" },
//     { group_code: "CM04", code: "CM0407", name: "cms", description: "CMS", order_seq: 7, is_use: "Y" },
//     { group_code: "CM04", code: "CM0408", name: "4dml", description: "FDML", order_seq: 8, is_use: "Y" },
//     { group_code: "CM04", code: "CM0409", name: "cms_w", description: "CMS_W", order_seq: 9, is_use: "Y" },
//     { group_code: "CM04", code: "CM0410", name: "ims", description: "IMS", order_seq: 10, is_use: "Y" },
//     {
//       group_code: "CM04",
//       code: "CM0411",
//       name: "prewarmer",
//       description: "PREWARM",
//       order_seq: 11,
//       is_use: "Y",
//     },
//     { group_code: "CM05", code: "CM0501", name: "pause", description: "PAUSE", order_seq: 1, is_use: "Y" },
//     { group_code: "CM05", code: "CM0502", name: "resume", description: "RESUME", order_seq: 2, is_use: "Y" },
//     { group_code: "CM05", code: "CM0503", name: "end", description: "END", order_seq: 3, is_use: "Y" },
//     { group_code: "CM06", code: "CM0601", name: "running", description: "RUNNING", order_seq: 1, is_use: "Y" },
//     {
//       group_code: "CM06",
//       code: "CM0602",
//       name: "temporary",
//       description: "TEMPORARY",
//       order_seq: 2,
//       is_use: "Y",
//     },
//     {
//       group_code: "CM06",
//       code: "CM0603",
//       name: "terminated",
//       description: "TERMINATED",
//       order_seq: 3,
//       is_use: "Y",
//     },
//     {
//       group_code: "CM07",
//       code: "us-east-1",
//       name: "VIR",
//       description: "미국동부 버지니아 북부",
//       order_seq: 1,
//       is_use: "Y",
//     },
//     {
//       group_code: "CM07",
//       code: "us-east-2",
//       name: "OH",
//       description: "미국동부 오하이오",
//       order_seq: 2,
//       is_use: "Y",
//     },
//     {
//       group_code: "CM07",
//       code: "us-west-1",
//       name: "CAL",
//       description: "미국서부 캘리포니아",
//       order_seq: 3,
//       is_use: "Y",
//     },
//     {
//       group_code: "CM07",
//       code: "us-west-2",
//       name: "OR",
//       description: "미국서부오레곤",
//       order_seq: 4,
//       is_use: "Y",
//     },
//     {
//       group_code: "CM07",
//       code: "ap-northeast-2",
//       name: "KR",
//       description: "아시아태평양 서울",
//       order_seq: 5,
//       is_use: "Y",
//     },
//     {
//       group_code: "CM07",
//       code: "ap-southeast-1",
//       name: "SIN",
//       description: "아시아태평양 싱가포르",
//       order_seq: 6,
//       is_use: "Y",
//     },
//     {
//       group_code: "CM07",
//       code: "ap-southeast-2",
//       name: "SYD",
//       description: "아시아태평양 시드니",
//       order_seq: 7,
//       is_use: "Y",
//     },
//     {
//       group_code: "CM07",
//       code: "ap-northeast-1",
//       name: "JP",
//       description: "아시아태평양 도쿄",
//       order_seq: 8,
//       is_use: "Y",
//     },
//     {
//       group_code: "CM07",
//       code: "ca-central-1",
//       name: "CAN",
//       description: "캐나다 중부",
//       order_seq: 9,
//       is_use: "Y",
//     },
//     {
//       group_code: "CM07",
//       code: "eu-central-1",
//       name: "GER",
//       description: "유럽 프랑크푸르트",
//       order_seq: 10,
//       is_use: "Y",
//     },
//     { group_code: "CM07", code: "eu-west-2", name: "UK", description: "유럽 런던", order_seq: 11, is_use: "Y" },
//     {
//       group_code: "CM07",
//       code: "eu-south-1",
//       name: "ITA",
//       description: "유럽 밀라노",
//       order_seq: 12,
//       is_use: "Y",
//     },
//     {
//       group_code: "CM07",
//       code: "eu-west-3",
//       name: "FRA",
//       description: "유럽 파리",
//       order_seq: 13,
//       is_use: "Y",
//     },
//     {
//       group_code: "CM07",
//       code: "ap-east-1",
//       name: "HK",
//       description: "아시아태평양 홍콩",
//       order_seq: 14,
//       is_use: "Y",
//     },
//     {
//       group_code: "CM07",
//       code: "af-south-1",
//       name: "KT",
//       description: "아프리카 케이프타운",
//       order_seq: 15,
//       is_use: "Y",
//     },
//     {
//       group_code: "CM07",
//       code: "ap-south-1",
//       name: "MB",
//       description: "아시아태평양 뭄바이",
//       order_seq: 16,
//       is_use: "Y",
//     },
//     {
//       group_code: "CM07",
//       code: "ap-northeast-3",
//       name: "OS",
//       description: "아시아태평양 오사카",
//       order_seq: 17,
//       is_use: "Y",
//     },
//     {
//       group_code: "CM07",
//       code: "eu-west-1",
//       name: "IL",
//       description: "유럽 아일랜드",
//       order_seq: 18,
//       is_use: "Y",
//     },
//     {
//       group_code: "CM07",
//       code: "eu-north-1",
//       name: "SH",
//       description: "유럽 스톡홀름",
//       order_seq: 19,
//       is_use: "Y",
//     },
//     {
//       group_code: "CM07",
//       code: "me-south-1",
//       name: "BA",
//       description: "중동 바레인",
//       order_seq: 20,
//       is_use: "Y",
//     },
//     {
//       group_code: "CM07",
//       code: "sa-east-1",
//       name: "BRA",
//       description: "남아메리카 상파울루",
//       order_seq: 21,
//       is_use: "Y",
//     },
//     { group_code: "CM08", code: "CM0801", name: "master", description: "MASTER", order_seq: 1, is_use: "Y" },
//     { group_code: "CM08", code: "CM0802", name: "slave", description: "SLAVE", order_seq: 2, is_use: "Y" },
//     { group_code: "CM09", code: "CM0901", name: "enable", description: "ENABLE", order_seq: 1, is_use: "Y" },
//     { group_code: "CM09", code: "CM0902", name: "disable", description: "DISABLE", order_seq: 2, is_use: "Y" },
//     { group_code: "CM10", code: "CM1001", name: "1", description: "MAINVIEW", order_seq: 1, is_use: "Y" },
//     { group_code: "CM10", code: "CM1002", name: "2", description: "SUBVIEW", order_seq: 2, is_use: "Y" },
//     { group_code: "CM11", code: "CM1101", name: "1", description: "VIDEO", order_seq: 1, is_use: "Y" },
//     { group_code: "CM11", code: "CM1102", name: "2", description: "AUDIO", order_seq: 2, is_use: "Y" },
//     { group_code: "CM11", code: "CM1103", name: "3", description: "ALL", order_seq: 3, is_use: "Y" },
//     { group_code: "CM12", code: "CM1201", name: "1", description: "모노", order_seq: 1, is_use: "Y" },
//     { group_code: "CM12", code: "CM1202", name: "2", description: "스테레오", order_seq: 2, is_use: "Y" },
//     { group_code: "CM12", code: "CM1203", name: "3", description: "서라운드", order_seq: 3, is_use: "Y" },
//     {
//       group_code: "CM13",
//       code: "CM1301",
//       name: "MAINVIEWA",
//       description: "MAINVIEWA",
//       order_seq: 1,
//       is_use: "Y",
//     },
//     {
//       group_code: "CM13",
//       code: "CM1302",
//       name: "MAINVIEWB",
//       description: "MAINVIEWB",
//       order_seq: 2,
//       is_use: "Y",
//     },
//     {
//       group_code: "CM13",
//       code: "CM1303",
//       name: "MAINVIEWC",
//       description: "MAINVIEWC",
//       order_seq: 3,
//       is_use: "Y",
//     },
//     {
//       group_code: "CM13",
//       code: "CM1304",
//       name: "MAINVIEWD",
//       description: "MAINVIEWD",
//       order_seq: 4,
//       is_use: "Y",
//     },
//     {
//       group_code: "CM13",
//       code: "CM1305",
//       name: "MAINVIEWE",
//       description: "MAINVIEWE",
//       order_seq: 5,
//       is_use: "Y",
//     },
//     {
//       group_code: "CM13",
//       code: "CM1306",
//       name: "MAINVIEWF",
//       description: "MAINVIEWF",
//       order_seq: 6,
//       is_use: "Y",
//     },
//     {
//       group_code: "CM13",
//       code: "CM1307",
//       name: "MAINVIEWG",
//       description: "MAINVIEWG",
//       order_seq: 7,
//       is_use: "Y",
//     },
//     {
//       group_code: "CM13",
//       code: "CM1308",
//       name: "MAINVIEWH",
//       description: "MAINVIEWH",
//       order_seq: 8,
//       is_use: "Y",
//     },
//     {
//       group_code: "CM13",
//       code: "CM1309",
//       name: "MAINVIEWI",
//       description: "MAINVIEWI",
//       order_seq: 9,
//       is_use: "Y",
//     },
//     {
//       group_code: "CM13",
//       code: "CM1310",
//       name: "MAINVIEWJ",
//       description: "MAINVIEWJ",
//       order_seq: 10,
//       is_use: "Y",
//     },
//     {
//       group_code: "CM13",
//       code: "CM1311",
//       name: "MULTIVIEWA",
//       description: "MULTIVIEWA",
//       order_seq: 11,
//       is_use: "Y",
//     },
//     {
//       group_code: "CM13",
//       code: "CM1312",
//       name: "MULTIVIEWB",
//       description: "MULTIVIEWB",
//       order_seq: 12,
//       is_use: "Y",
//     },
//     {
//       group_code: "CM13",
//       code: "CM1313",
//       name: "MULTIVIEWC",
//       description: "MULTIVIEWC",
//       order_seq: 13,
//       is_use: "Y",
//     },
//     {
//       group_code: "CM13",
//       code: "CM1314",
//       name: "MULTIVIEWD",
//       description: "MULTIVIEWD",
//       order_seq: 14,
//       is_use: "Y",
//     },
//     {
//       group_code: "CM13",
//       code: "CM1315",
//       name: "MULTIVIEWE",
//       description: "MULTIVIEWE",
//       order_seq: 15,
//       is_use: "Y",
//     },
//     {
//       group_code: "CM13",
//       code: "CM1316",
//       name: "MULTIVIEWF",
//       description: "MULTIVIEWF",
//       order_seq: 16,
//       is_use: "Y",
//     },
//     {
//       group_code: "CM13",
//       code: "CM1317",
//       name: "BIRDVIEWA",
//       description: "BIRDVIEWA",
//       order_seq: 17,
//       is_use: "Y",
//     },
//     {
//       group_code: "CM13",
//       code: "CM1318",
//       name: "BIRDVIEWB",
//       description: "BIRDVIEWB",
//       order_seq: 18,
//       is_use: "Y",
//     },
//     {
//       group_code: "CM13",
//       code: "CM1319",
//       name: "BIRDVIEWC",
//       description: "BIRDVIEWC",
//       order_seq: 19,
//       is_use: "Y",
//     },
//     {
//       group_code: "CM13",
//       code: "CM1320",
//       name: "EXTERNALA",
//       description: "EXTERNALA",
//       order_seq: 20,
//       is_use: "Y",
//     },
//     {
//       group_code: "CM13",
//       code: "CM1321",
//       name: "EXTERNALB",
//       description: "EXTERNALB",
//       order_seq: 21,
//       is_use: "Y",
//     },
//     {
//       group_code: "CM13",
//       code: "CM1322",
//       name: "EXTERNALC",
//       description: "EXTERNALC",
//       order_seq: 22,
//       is_use: "Y",
//     },
//     { group_code: "CM13", code: "CM1323", name: "PDVIEWA", description: "PDVIEWA", order_seq: 23, is_use: "Y" },
//     { group_code: "CM13", code: "CM1324", name: "PDVIEWB", description: "PDVIEWB", order_seq: 24, is_use: "Y" },
//     { group_code: "CM13", code: "CM1325", name: "PDVIEWC", description: "PDVIEWC", order_seq: 25, is_use: "Y" },
//     {
//       group_code: "CM13",
//       code: "CM1326",
//       name: "MULTIVIEWA-AUDIO",
//       description: "MULTIVIEWA-AUDIO",
//       order_seq: 26,
//       is_use: "Y",
//     },
//     {
//       group_code: "CM13",
//       code: "CM1327",
//       name: "MULTIVIEWB-AUDIO",
//       description: "MULTIVIEWB-AUDIO",
//       order_seq: 27,
//       is_use: "Y",
//     },
//     {
//       group_code: "CM13",
//       code: "CM1328",
//       name: "MULTIVIEWC-AUDIO",
//       description: "MULTIVIEWC-AUDIO",
//       order_seq: 28,
//       is_use: "Y",
//     },
//     {
//       group_code: "CM13",
//       code: "CM1329",
//       name: "MULTIVIEWD-AUDIO",
//       description: "MULTIVIEWD-AUDIO",
//       order_seq: 29,
//       is_use: "Y",
//     },
//     {
//       group_code: "CM13",
//       code: "CM1330",
//       name: "MULTIVIEWE-AUDIO",
//       description: "MULTIVIEWE-AUDIO",
//       order_seq: 30,
//       is_use: "Y",
//     },
//     {
//       group_code: "CM13",
//       code: "CM1331",
//       name: "MULTIVIEWF-AUDIO",
//       description: "MULTIVIEWF-AUDIO",
//       order_seq: 31,
//       is_use: "Y",
//     },
//     {
//       group_code: "CM13",
//       code: "CM1332",
//       name: "EXTRAVIEWA",
//       description: "EXTRAVIEWA",
//       order_seq: 32,
//       is_use: "Y",
//     },
//     {
//       group_code: "CM13",
//       code: "CM1333",
//       name: "EXTRAVIEWB",
//       description: "EXTRAVIEWB",
//       order_seq: 33,
//       is_use: "Y",
//     },
//     {
//       group_code: "CM13",
//       code: "CM1334",
//       name: "EXTRAVIEWC",
//       description: "EXTRAVIEWC",
//       order_seq: 34,
//       is_use: "Y",
//     },
//     { group_code: "CM14", code: "CM1401", name: "1", description: "Dispatcher", order_seq: 1, is_use: "Y" },
//     { group_code: "CM14", code: "CM1402", name: "2", description: "EMSG", order_seq: 2, is_use: "Y" },
//     {
//       group_code: "CM14",
//       code: "CM1403",
//       name: "3",
//       description: "4DML_Media_Pipeline",
//       order_seq: 3,
//       is_use: "Y",
//     },
//     { group_code: "CM14", code: "CM1404", name: "4", description: "Vod_Pipeline", order_seq: 4, is_use: "Y" },
//     { group_code: "CM14", code: "CM1405", name: "5", description: "iVod_PipeLine", order_seq: 5, is_use: "Y" },
//     { group_code: "CM14", code: "CM1406", name: "6", description: "Mediastore", order_seq: 6, is_use: "Y" },
//     { group_code: "CM14", code: "CM1407", name: "7", description: "4DML_Manager", order_seq: 7, is_use: "Y" },
//     { group_code: "CM14", code: "CM1408", name: "8", description: "CLOUD_FRONT", order_seq: 8, is_use: "Y" },
//     {
//       group_code: "CM15",
//       code: "CM1501",
//       name: "mediastore",
//       description: "MEDIASTORE",
//       order_seq: 1,
//       is_use: "Y",
//     },
//     { group_code: "CM15", code: "CM1502", name: "s3", description: "S3", order_seq: 2, is_use: "Y" },
//     {
//       group_code: "CM15",
//       code: "CM1503",
//       name: "file_server",
//       description: "FILE_SERVER",
//       order_seq: 3,
//       is_use: "Y",
//     },
//   ]);
//
//   // Deletes ALL existing entries
//   await knex("code_group").del();
//
//   // Inserts code_group seed entries
//   await knex("code_group").insert([
//     { code: "CM01", name: "여부코드", description: "유무 코드", order_seq: 1, is_use: "Y" },
//     { code: "CM02", name: "라이브상태", description: "라이브 상태 코드", order_seq: 2, is_use: "Y" },
//     { code: "CM03", name: "채널상태", description: "채널 상태 코드", order_seq: 3, is_use: "Y" },
//     { code: "CM04", name: "노드유형", description: "노드 유형 코드", order_seq: 4, is_use: "Y" },
//     { code: "CM05", name: "이벤트상태", description: "이벤트상태코드", order_seq: 5, is_use: "Y" },
//     { code: "CM06", name: "AWS인스턴스상태", description: "AWS인스턴스상태", order_seq: 6, is_use: "Y" },
//     { code: "CM07", name: "리전정보", description: "리전정보", order_seq: 7, is_use: "Y" },
//     { code: "CM08", name: "4DLS유형", description: "4인 유형 코드", order_seq: 8, is_use: "Y" },
//     { code: "CM09", name: "nodeStatus", description: "nodeStatus", order_seq: 9, is_use: "Y" },
//     { code: "CM10", name: "그룹유형", description: "그룹유형", order_seq: 10, is_use: "Y" },
//     { code: "CM11", name: "미디어유형", description: "미디어유형", order_seq: 11, is_use: "Y" },
//     { code: "CM12", name: "오디오채널유형", description: "오디오채널유형", order_seq: 12, is_use: "Y" },
//     { code: "CM13", name: "viewType", description: "viewType", order_seq: 13, is_use: "Y" },
//     { code: "CM14", name: "4DML유형", description: "4DML유형", order_seq: 14, is_use: "Y" },
//     { code: "CM15", name: "deployType", description: "deployType", order_seq: 15, is_use: "Y" },
//   ]);
//
//   // world_country, world_state, world_city seed insert
//   await knex("world_country").del();
//   await knex("world_country").insert(worldCountries);
//
//   await knex("world_state").del();
//   await knex("world_state").insert(worldStates);
//
//   await knex("world_city").del();
//   await knex("world_city").insert(worldCities);
//
//   // const worldCountryUpdateSeeds = [
//   //   { id: 1, code: 4 },
//   //   { id: 2, code: 248 },
//   //   { id: 3, code: 8 },
//   //   { id: 4, code: 12 },
//   //   { id: 5, code: 16 },
//   //   { id: 6, code: 20 },
//   //   { id: 7, code: 24 },
//   //   { id: 8, code: 660 },
//   //   { id: 9, code: 10 },
//   //   { id: 10, code: 28 },
//   //   { id: 11, code: 32 },
//   //   { id: 12, code: 51 },
//   //   { id: 13, code: 533 },
//   //   { id: 14, code: 36 },
//   //   { id: 15, code: 40 },
//   //   { id: 16, code: 31 },
//   //   { id: 17, code: 44 },
//   //   { id: 18, code: 48 },
//   //   { id: 19, code: 50 },
//   //   { id: 20, code: 52 },
//   //   { id: 21, code: 112 },
//   //   { id: 22, code: 56 },
//   //   { id: 23, code: 84 },
//   //   { id: 24, code: 204 },
//   //   { id: 25, code: 60 },
//   //   { id: 26, code: 64 },
//   //   { id: 27, code: 68 },
//   //   { id: 28, code: 70 },
//   //   { id: 29, code: 72 },
//   //   { id: 30, code: 74 },
//   //   { id: 31, code: 76 },
//   //   { id: 32, code: 86 },
//   //   { id: 33, code: 96 },
//   //   { id: 34, code: 100 },
//   //   { id: 35, code: 854 },
//   //   { id: 36, code: 108 },
//   //   { id: 37, code: 116 },
//   //   { id: 38, code: 120 },
//   //   { id: 39, code: 124 },
//   //   { id: 41, code: 136 },
//   //   { id: 42, code: 140 },
//   //   { id: 43, code: 148 },
//   //   { id: 44, code: 152 },
//   //   { id: 45, code: 156 },
//   //   { id: 46, code: 162 },
//   //   { id: 47, code: 166 },
//   //   { id: 48, code: 170 },
//   //   { id: 49, code: 174 },
//   //   { id: 50, code: 178 },
//   //   { id: 51, code: 180 },
//   //   { id: 52, code: 184 },
//   //   { id: 53, code: 188 },
//   //   { id: 54, code: 384 },
//   //   { id: 55, code: 191 },
//   //   { id: 56, code: 192 },
//   //   { id: 57, code: 196 },
//   //   { id: 58, code: 203 },
//   //   { id: 59, code: 208 },
//   //   { id: 60, code: 262 },
//   //   { id: 61, code: 212 },
//   //   { id: 62, code: 214 },
//   //   { id: 63, code: 626 },
//   //   { id: 64, code: 218 },
//   //   { id: 65, code: 818 },
//   //   { id: 66, code: 222 },
//   //   { id: 67, code: 226 },
//   //   { id: 68, code: 232 },
//   //   { id: 69, code: 233 },
//   //   { id: 70, code: 231 },
//   //   { id: 71, code: 238 },
//   //   { id: 72, code: 234 },
//   //   { id: 73, code: 242 },
//   //   { id: 74, code: 246 },
//   //   { id: 75, code: 250 },
//   //   { id: 76, code: 254 },
//   //   { id: 77, code: 258 },
//   //   { id: 78, code: 260 },
//   //   { id: 79, code: 266 },
//   //   { id: 80, code: 270 },
//   //   { id: 81, code: 268 },
//   //   { id: 82, code: 276 },
//   //   { id: 83, code: 288 },
//   //   { id: 84, code: 292 },
//   //   { id: 85, code: 300 },
//   //   { id: 86, code: 304 },
//   //   { id: 87, code: 308 },
//   //   { id: 88, code: 312 },
//   //   { id: 89, code: 316 },
//   //   { id: 90, code: 320 },
//   //   { id: 91, code: 831 },
//   //   { id: 92, code: 324 },
//   //   { id: 93, code: 624 },
//   //   { id: 94, code: 328 },
//   //   { id: 95, code: 332 },
//   //   { id: 96, code: 334 },
//   //   { id: 97, code: 340 },
//   //   { id: 98, code: 344 },
//   //   { id: 99, code: 348 },
//   //   { id: 100, code: 352 },
//   //   { id: 101, code: 356 },
//   //   { id: 102, code: 360 },
//   //   { id: 103, code: 364 },
//   //   { id: 104, code: 368 },
//   //   { id: 105, code: 372 },
//   //   { id: 106, code: 376 },
//   //   { id: 107, code: 380 },
//   //   { id: 108, code: 388 },
//   //   { id: 109, code: 392 },
//   //   { id: 110, code: 832 },
//   //   { id: 111, code: 400 },
//   //   { id: 112, code: 398 },
//   //   { id: 113, code: 404 },
//   //   { id: 114, code: 296 },
//   //   { id: 115, code: 408 },
//   //   { id: 116, code: 410 },
//   //   { id: 117, code: 414 },
//   //   { id: 118, code: 417 },
//   //   { id: 119, code: 418 },
//   //   { id: 120, code: 428 },
//   //   { id: 121, code: 422 },
//   //   { id: 122, code: 426 },
//   //   { id: 123, code: 430 },
//   //   { id: 124, code: 434 },
//   //   { id: 125, code: 438 },
//   //   { id: 126, code: 440 },
//   //   { id: 127, code: 442 },
//   //   { id: 128, code: 446 },
//   //   { id: 129, code: 807 },
//   //   { id: 130, code: 450 },
//   //   { id: 131, code: 454 },
//   //   { id: 132, code: 458 },
//   //   { id: 133, code: 462 },
//   //   { id: 134, code: 466 },
//   //   { id: 135, code: 470 },
//   //   { id: 137, code: 584 },
//   //   { id: 138, code: 474 },
//   //   { id: 139, code: 478 },
//   //   { id: 140, code: 480 },
//   //   { id: 141, code: 175 },
//   //   { id: 142, code: 484 },
//   //   { id: 143, code: 583 },
//   //   { id: 144, code: 498 },
//   //   { id: 145, code: 492 },
//   //   { id: 146, code: 496 },
//   //   { id: 147, code: 499 },
//   //   { id: 148, code: 500 },
//   //   { id: 149, code: 504 },
//   //   { id: 150, code: 508 },
//   //   { id: 151, code: 104 },
//   //   { id: 152, code: 516 },
//   //   { id: 153, code: 520 },
//   //   { id: 154, code: 524 },
//   //   { id: 156, code: 528 },
//   //   { id: 157, code: 540 },
//   //   { id: 158, code: 554 },
//   //   { id: 159, code: 558 },
//   //   { id: 160, code: 562 },
//   //   { id: 161, code: 566 },
//   //   { id: 162, code: 570 },
//   //   { id: 163, code: 574 },
//   //   { id: 164, code: 580 },
//   //   { id: 165, code: 578 },
//   //   { id: 166, code: 512 },
//   //   { id: 167, code: 586 },
//   //   { id: 168, code: 585 },
//   //   { id: 169, code: 275 },
//   //   { id: 170, code: 591 },
//   //   { id: 171, code: 598 },
//   //   { id: 172, code: 600 },
//   //   { id: 173, code: 604 },
//   //   { id: 174, code: 608 },
//   //   { id: 175, code: 612 },
//   //   { id: 176, code: 616 },
//   //   { id: 177, code: 620 },
//   //   { id: 178, code: 630 },
//   //   { id: 179, code: 634 },
//   //   { id: 180, code: 638 },
//   //   { id: 181, code: 642 },
//   //   { id: 182, code: 643 },
//   //   { id: 183, code: 646 },
//   //   { id: 184, code: 654 },
//   //   { id: 185, code: 659 },
//   //   { id: 186, code: 662 },
//   //   { id: 187, code: 666 },
//   //   { id: 188, code: 670 },
//   //   { id: 191, code: 882 },
//   //   { id: 192, code: 674 },
//   //   { id: 193, code: 678 },
//   //   { id: 194, code: 682 },
//   //   { id: 195, code: 686 },
//   //   { id: 196, code: 688 },
//   //   { id: 197, code: 690 },
//   //   { id: 198, code: 694 },
//   //   { id: 199, code: 702 },
//   //   { id: 200, code: 703 },
//   //   { id: 201, code: 705 },
//   //   { id: 202, code: 90 },
//   //   { id: 203, code: 706 },
//   //   { id: 204, code: 710 },
//   //   { id: 205, code: 239 },
//   //   { id: 206, code: 728 },
//   //   { id: 207, code: 724 },
//   //   { id: 208, code: 144 },
//   //   { id: 209, code: 729 },
//   //   { id: 210, code: 740 },
//   //   { id: 211, code: 744 },
//   //   { id: 212, code: 748 },
//   //   { id: 213, code: 752 },
//   //   { id: 214, code: 756 },
//   //   { id: 215, code: 760 },
//   //   { id: 216, code: 158 },
//   //   { id: 217, code: 762 },
//   //   { id: 218, code: 834 },
//   //   { id: 219, code: 764 },
//   //   { id: 220, code: 768 },
//   //   { id: 221, code: 772 },
//   //   { id: 222, code: 776 },
//   //   { id: 223, code: 780 },
//   //   { id: 224, code: 788 },
//   //   { id: 225, code: 792 },
//   //   { id: 226, code: 795 },
//   //   { id: 227, code: 796 },
//   //   { id: 228, code: 798 },
//   //   { id: 229, code: 800 },
//   //   { id: 230, code: 804 },
//   //   { id: 231, code: 784 },
//   //   { id: 232, code: 826 },
//   //   { id: 233, code: 840 },
//   //   { id: 234, code: 581 },
//   //   { id: 235, code: 858 },
//   //   { id: 236, code: 860 },
//   //   { id: 237, code: 548 },
//   //   { id: 239, code: 862 },
//   //   { id: 240, code: 704 },
//   //   { id: 241, code: 92 },
//   //   { id: 242, code: 850 },
//   //   { id: 243, code: 876 },
//   //   { id: 244, code: 732 },
//   //   { id: 245, code: 887 },
//   //   { id: 246, code: 894 },
//   //   { id: 247, code: 716 },
//   // ];
//   //
//   // for (const elem of worldCountryUpdateSeeds) {
//   //   await knex("world_country").update({ id: `${elem.id}`, code: `${elem.code}` });
//   // }
//
//   // other updates
//   await knex("node").update("id", `CONCAT(system_id, LPAD(id, 3, '0'))`);
//   await knex("node").update(
//     "parent_node_id",
//     `IF(parent_node_id = 0, NULL, CONCAT(system_id,  LPAD(parent_node_id, 3, '0')))`,
//   );
//   await knex("rule").update("id", `CONCAT(system_id, LPAD(id, 3, '0'))`);
//   await knex("scale").update("id", `CONCAT(system_id, LPAD(id, 3, '0'))`);
//   await knex("channel").update("id", `CONCAT(system_id, LPAD(id, 3, '0'))`);
//   await knex("channel").update("group_id", `CONCAT(system_id, LPAD(id, 3, '0'))`);
//   await knex("video").update(
//     "id",
//     `CONCAT((SELECT system_id FROM groups WHERE id = group_id),  LPAD( RIGHT( id, 3 ), 3, '0'))`,
//   );
//   await knex("video").update(
//     "group_id",
//     `CONCAT((SELECT system_id FROM groups WHERE id = group_id),  LPAD( group_id, 3, '0'))`,
//   );
//   await knex("audio").update(
//     "id",
//     `CONCAT((SELECT system_id FROM groups WHERE id = group_id),  LPAD( RIGHT( id, 3 ), 3, '0'))`,
//   );
//   await knex("audio").update(
//     "group_id",
//     `CONCAT((SELECT system_id FROM groups WHERE id = group_id),  LPAD( group_id, 3, '0'))`,
//   );
//   await knex("adaptive_streaming").update(
//     "id",
//     `CONCAT((SELECT system_id FROM groups WHERE id = group_id),  LPAD( RIGHT( id, 3 ), 3, '0'))`,
//   );
//   await knex("adaptive_streaming").update(
//     "group_id",
//     `CONCAT((SELECT system_id FROM groups WHERE id = group_id),  LPAD( group_id , 3, '0'))`,
//   );
//   await knex("groups").update("id", `CONCAT(system_id, LPAD(id, 3, '0')`);
// }
